# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('admin', models.BooleanField(max_length=250)),
                ('event_details', models.CharField(max_length=500)),
                ('createdDate', models.DateField()),
                ('lastUpdetedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=1000)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
